### ISSUE TITLE
希望原点重设

### ISSUE THREAD

**Issue by xiaobaphage** [zhdbk3/PhotoAstrologicalPositioning#2]
原来是以图片正中心为原点，向右为x轴正方向，向下为y轴正方向
但是ps的XY是以照片左上角第一个像素为原点  以向右为x轴正方向，向下为y轴正方向
输入时还需手动修正
如有更好的软件请分享

**Comment by zhdbk3** [comment]
我今天在实际操作时也发现了这个问题，所以写了个坐标变换的工具，将在下个版本更新时一并发布

**Comment by zhdbk3** [comment]
已更新
https://github.com/zhdbk3/PhotoAstrologicalPositioning/releases/tag/v0.2
